DATABASE: 'https://graph-editor-database-default-rtdb.europe-west1.firebasedatabase.app/'
KEY_PATH: 'C:\Users\andre\OneDrive\Documents\GitHub\GraphEditor\FirebaseKey\graph-editor-database-firebase-adminsdk-fbsvc-1b066eac85.json'
API_KEY: 'AIzaSyAp5_l7wA6a__54DT8mUfH7RlNyoMLrHLI'
