# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_actions_btns = QtWidgets.QFrame(self.centralwidget)
        self.frame_actions_btns.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_actions_btns.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_actions_btns.setStyleSheet("QFrame{\n"
"    background-color: rgb(35, 39, 42);\n"
"}")
        self.frame_actions_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_actions_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_actions_btns.setObjectName("frame_actions_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_actions_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(809, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_btns = QtWidgets.QFrame(self.frame_actions_btns)
        self.frame_btns.setMinimumSize(QtCore.QSize(75, 25))
        self.frame_btns.setMaximumSize(QtCore.QSize(75, 25))
        self.frame_btns.setStyleSheet("")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_minimize = QtWidgets.QLabel(self.frame_btns)
        self.label_minimize.setMinimumSize(QtCore.QSize(25, 25))
        self.label_minimize.setMaximumSize(QtCore.QSize(25, 25))
        self.label_minimize.setStyleSheet("QLabel{\n"
"    image: url(:/icons/icons/cil-minus.png);\n"
"}\n"
"QLabel::hover{\n"
"    background-color: rgb(44, 47, 51);\n"
"}")
        self.label_minimize.setText("")
        self.label_minimize.setObjectName("label_minimize")
        self.horizontalLayout_3.addWidget(self.label_minimize)
        self.label_maximize = QtWidgets.QLabel(self.frame_btns)
        self.label_maximize.setMinimumSize(QtCore.QSize(25, 25))
        self.label_maximize.setMaximumSize(QtCore.QSize(25, 25))
        self.label_maximize.setStyleSheet("QLabel{\n"
"    image: url(:/icons/icons/cil-window-maximize.png);\n"
"}\n"
"QLabel::hover{\n"
"    background-color: rgb(44, 47, 51);\n"
"}")
        self.label_maximize.setText("")
        self.label_maximize.setObjectName("label_maximize")
        self.horizontalLayout_3.addWidget(self.label_maximize)
        self.label_close = QtWidgets.QLabel(self.frame_btns)
        self.label_close.setMinimumSize(QtCore.QSize(25, 25))
        self.label_close.setMaximumSize(QtCore.QSize(25, 25))
        self.label_close.setStyleSheet("QLabel{\n"
"    image: url(:/icons/icons/cil-x.png);\n"
"}\n"
"QLabel::hover{\n"
"    background-color: red;\n"
"}")
        self.label_close.setText("")
        self.label_close.setObjectName("label_close")
        self.horizontalLayout_3.addWidget(self.label_close)
        self.horizontalLayout_2.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.frame_actions_btns)
        self.frame_central = QtWidgets.QFrame(self.centralwidget)
        self.frame_central.setStyleSheet("QFrame{\n"
"    background-color: rgb(35, 39, 42);\n"
"}")
        self.frame_central.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_central.setObjectName("frame_central")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_central)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_central_top = QtWidgets.QFrame(self.frame_central)
        self.frame_central_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_central_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_central_top.setStyleSheet("QFrame{\n"
"    background-color: rgb(99, 103, 110);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_central_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_central_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_central_top.setObjectName("frame_central_top")
        self.frame_settings = QtWidgets.QFrame(self.frame_central_top)
        self.frame_settings.setGeometry(QtCore.QRect(0, 0, 295, 50))
        self.frame_settings.setStyleSheet("QFrame{\n"
"    background-color: rgb(99, 103, 110);\n"
"    border-radius: 20px;\n"
"}")
        self.frame_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings.setObjectName("frame_settings")
        self.label_options = QtWidgets.QLabel(self.frame_settings)
        self.label_options.setGeometry(QtCore.QRect(0, 0, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_options.sizePolicy().hasHeightForWidth())
        self.label_options.setSizePolicy(sizePolicy)
        self.label_options.setMinimumSize(QtCore.QSize(50, 50))
        self.label_options.setMaximumSize(QtCore.QSize(50, 50))
        self.label_options.setStyleSheet("QLabel{\n"
"    image: url(:/icons/icons/cil-settings.png);\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel::hover{\n"
"    background-color: rgb(44, 47, 51);\n"
"}")
        self.label_options.setText("")
        self.label_options.setObjectName("label_options")
        self.frame_title = QtWidgets.QFrame(self.frame_central_top)
        self.frame_title.setGeometry(QtCore.QRect(294, 1, 292, 48))
        self.frame_title.setStyleSheet("QFrame{\n"
"    background-color: rgb(99, 103, 110);\n"
"}")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(50, 0))
        self.label_title.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_6.addWidget(self.label_title)
        self.frame_mode = QtWidgets.QFrame(self.frame_central_top)
        self.frame_mode.setGeometry(QtCore.QRect(586, 1, 293, 48))
        self.frame_mode.setStyleSheet("QFrame{\n"
"    background-color: rgb(99, 103, 110);\n"
"}")
        self.frame_mode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mode.setObjectName("frame_mode")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_mode)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_mode = QtWidgets.QLabel(self.frame_mode)
        self.label_mode.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label_mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mode.setObjectName("label_mode")
        self.horizontalLayout_5.addWidget(self.label_mode)
        self.pushButton_mode = QtWidgets.QPushButton(self.frame_mode)
        self.pushButton_mode.setMinimumSize(QtCore.QSize(55, 30))
        self.pushButton_mode.setMaximumSize(QtCore.QSize(55, 30))
        self.pushButton_mode.setObjectName("pushButton_mode")
        self.horizontalLayout_5.addWidget(self.pushButton_mode)
        self.verticalLayout_2.addWidget(self.frame_central_top)
        self.frame_graph = QtWidgets.QFrame(self.frame_central)
        self.frame_graph.setStyleSheet("")
        self.frame_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph.setObjectName("frame_graph")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_graph)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_node_data = QtWidgets.QFrame(self.frame_graph)
        self.frame_node_data.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_node_data.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_node_data.setStyleSheet("QFrame{\n"
"    background-color: rgb(99, 103, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_node_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_node_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_node_data.setObjectName("frame_node_data")
        self.horizontalLayout.addWidget(self.frame_node_data)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_graph)
        self.graphicsView.setStyleSheet("QGraphicsView{\n"
"    background-color: rgb(99, 103, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout_2.addWidget(self.frame_graph)
        self.verticalLayout.addWidget(self.frame_central)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "GRAPH EDITOR"))
        self.label_mode.setText(_translate("MainWindow", "DARK MODE"))
        self.pushButton_mode.setText(_translate("MainWindow", "PushButton"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
