from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtCore import pyqtSignal
from qtwidgets import AnimatedToggle


class ConfigPage(QtWidgets.QFrame):
    show_page = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("ConfigPage")
        self.setGeometry(QtCore.QRect(250, 140, 250, 481))
        self.setMinimumSize(QtCore.QSize(250, 0))
        self.setMaximumSize(QtCore.QSize(250, 16777215))
        self.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setStyleSheet("""
                    QFrame {
                        background-color: #63676e;
                        border-radius: 15px;
                    }
                """)

        self.verticalLayout_0 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_0.setObjectName("verticalLayout_0")

        self.frame_force_mode = QtWidgets.QFrame(self)
        self.frame_force_mode.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_force_mode.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_force_mode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_force_mode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_force_mode.setObjectName("frame_force_mode")
        self.horizontalLayout_3_0 = QtWidgets.QHBoxLayout(self.frame_force_mode)
        self.horizontalLayout_3_0.setObjectName("horizontalLayout_3_0")
        self.label_force_mode = QtWidgets.QLabel(self.frame_force_mode)
        self.label_force_mode.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.label_force_mode.setFont(font)
        self.label_force_mode.setStyleSheet("QLabel{\n    color: white;\n}")
        self.label_force_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_force_mode.setObjectName("label_force_mode")
        self.horizontalLayout_3_0.addWidget(self.label_force_mode)
        self.pushButton_force_mode = AnimatedToggle((self.frame_force_mode), pulse_checked_color="#95a5de",
                                                    checked_color="#7289da")
        self.pushButton_force_mode.setMinimumSize(QtCore.QSize(55, 30))
        self.pushButton_force_mode.setMaximumSize(QtCore.QSize(55, 30))
        self.pushButton_force_mode.setObjectName("pushButton_force_mode")
        self.horizontalLayout_3_0.addWidget(self.pushButton_force_mode)
        self.verticalLayout_0.addWidget(self.frame_force_mode)
        self.frame_node_radius = QtWidgets.QFrame(self)
        self.frame_node_radius.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_node_radius.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_node_radius.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_node_radius.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_node_radius.setObjectName("frame_node_radius")
        self.horizontalLayout_4_0 = QtWidgets.QHBoxLayout(self.frame_node_radius)
        self.horizontalLayout_4_0.setObjectName("horizontalLayout_4_0")
        self.label_node_radius = QtWidgets.QLabel(self.frame_node_radius)
        self.label_node_radius.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.label_node_radius.setFont(font)
        self.label_node_radius.setStyleSheet("QLabel{\n    color: white;\n}")
        self.label_node_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.label_node_radius.setObjectName("label_node_radius")
        self.horizontalLayout_4_0.addWidget(self.label_node_radius)
        self.spinBox_node_radius = QtWidgets.QSpinBox(self.frame_node_radius)
        self.spinBox_node_radius.setMinimumSize(QtCore.QSize(50, 20))
        self.spinBox_node_radius.setMaximumSize(QtCore.QSize(50, 20))
        self.spinBox_node_radius.setStyleSheet(
            'QSpinBox{\n    background-color: transparent;\n    border: none;\n    border-bottom: 2px solid white;\n    border-bottom-style: solid; \n    color:  white;\n    font: 63 14pt "Segoe UI Semibold";\n}')
        self.spinBox_node_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_node_radius.setObjectName("spinBox_node_radius")
        self.horizontalLayout_4_0.addWidget(self.spinBox_node_radius)
        self.verticalLayout_0.addWidget(self.frame_node_radius)
        self.frame_DFS = QtWidgets.QFrame(self)
        self.frame_DFS.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_DFS.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_DFS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DFS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DFS.setObjectName("frame_DFS")
        self.horizontalLayout_2_0 = QtWidgets.QHBoxLayout(self.frame_DFS)
        self.horizontalLayout_2_0.setObjectName("horizontalLayout_2_0")
        self.label_DFS = QtWidgets.QLabel(self.frame_DFS)
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.label_DFS.setFont(font)
        self.label_DFS.setStyleSheet("QLabel{\n    color: white;\n}")
        self.label_DFS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DFS.setObjectName("label_DFS")
        self.horizontalLayout_2_0.addWidget(self.label_DFS)
        self.lineEdit_DFS = QtWidgets.QLineEdit(self.frame_DFS)
        self.lineEdit_DFS.setMinimumSize(QtCore.QSize(55, 30))
        self.lineEdit_DFS.setMaximumSize(QtCore.QSize(55, 30))
        self.lineEdit_DFS.setStyleSheet(
            'QLineEdit{\n    background-color: transparent;\n    border: none;\n    border-bottom: 2px solid white;\n    border-bottom-style: solid; \n    color:  white;\n    font: 63 14pt "Segoe UI Semibold";\n}')
        self.lineEdit_DFS.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DFS.setObjectName("lineEdit_DFS")
        self.horizontalLayout_2_0.addWidget(self.lineEdit_DFS)
        self.pushButton_clear_DFS = QtWidgets.QPushButton(self.frame_DFS)
        self.pushButton_clear_DFS.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_clear_DFS.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_clear_DFS.setStyleSheet("QPushButton{\nbackground-color: transparent;\nborder-radius: 5px;\n}"
                                                "QPushButton::hover{\nbackground-color: rgb(44, 47, 51);\n}")
        self.pushButton_clear_DFS.setIcon(QtGui.QIcon("icons/cil-remove.png"))
        self.pushButton_clear_DFS.setObjectName("pushButton_clear_DFS")
        self.horizontalLayout_2_0.addWidget(self.pushButton_clear_DFS)
        self.verticalLayout_0.addWidget(self.frame_DFS)
        self.frame_BFS = QtWidgets.QFrame(self)
        self.frame_BFS.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_BFS.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_BFS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BFS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BFS.setObjectName("frame_BFS")
        self.horizontalLayout_0 = QtWidgets.QHBoxLayout(self.frame_BFS)
        self.horizontalLayout_0.setObjectName("horizontalLayout_0")
        self.label_BFS = QtWidgets.QLabel(self.frame_BFS)
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.label_BFS.setFont(font)
        self.label_BFS.setStyleSheet("QLabel{\n    color: white;\n}")
        self.label_BFS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BFS.setObjectName("label_BFS")
        self.horizontalLayout_0.addWidget(self.label_BFS)
        self.lineEdit_BFS = QtWidgets.QLineEdit(self.frame_BFS)
        self.lineEdit_BFS.setMinimumSize(QtCore.QSize(55, 30))
        self.lineEdit_BFS.setMaximumSize(QtCore.QSize(55, 30))
        self.lineEdit_BFS.setStyleSheet(
            'QLineEdit{\n    background-color: transparent;\n    border: none;\n    border-bottom: 2px solid white;\n    border-bottom-style: solid; \n    color:  white;\n    font: 63 14pt "Segoe UI Semibold";\n}')
        self.lineEdit_BFS.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_BFS.setObjectName("lineEdit_BFS")
        self.horizontalLayout_0.addWidget(self.lineEdit_BFS)
        self.pushButton_clear_BFS = QtWidgets.QPushButton(self.frame_BFS)
        self.pushButton_clear_BFS.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_clear_BFS.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_clear_BFS.setStyleSheet(
            "QPushButton{\nbackground-color: transparent;\nborder-radius: 5px;\n                                                    }\n                                                    QPushButton::hover{\n                                                    background-color: rgb(44, 47, 51);\n}")
        self.pushButton_clear_BFS.setIcon(QtGui.QIcon("icons/cil-remove.png"))
        self.pushButton_clear_BFS.setObjectName("pushButton_clear_DFS")
        self.horizontalLayout_0.addWidget(self.pushButton_clear_BFS)
        self.verticalLayout_0.addWidget(self.frame_BFS)
        self.frame_DIJKSTRA = QtWidgets.QFrame(self)
        self.frame_DIJKSTRA.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_DIJKSTRA.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_DIJKSTRA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DIJKSTRA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DIJKSTRA.setObjectName("frame_DIJKSTRA")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_DIJKSTRA)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_DIJKSTRA = QtWidgets.QLabel(self.frame_DIJKSTRA)
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.label_DIJKSTRA.setFont(font)
        self.label_DIJKSTRA.setStyleSheet("QLabel{\n    color: white;\n}")
        self.label_DIJKSTRA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DIJKSTRA.setObjectName("label_DIJKSTRA")
        self.horizontalLayout_10.addWidget(self.label_DIJKSTRA)
        self.lineEdit_DIJKSTRA_src = QtWidgets.QLineEdit(self.frame_DIJKSTRA)
        self.lineEdit_DIJKSTRA_src.setMinimumSize(QtCore.QSize(35, 30))
        self.lineEdit_DIJKSTRA_src.setMaximumSize(QtCore.QSize(35, 30))
        self.lineEdit_DIJKSTRA_src.setStyleSheet(
            'QLineEdit{\n    background-color: transparent;\n    border: none;\n    border-bottom: 2px solid white;\n    border-bottom-style: solid; \n    color:  white;\n    font: 63 14pt "Segoe UI Semibold";\n}')
        self.lineEdit_DIJKSTRA_src.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DIJKSTRA_src.setObjectName("lineEdit_DIJKSTRA_src")
        self.horizontalLayout_10.addWidget(self.lineEdit_DIJKSTRA_src)
        self.lineEdit_DIJKSTRA_end = QtWidgets.QLineEdit(self.frame_DIJKSTRA)
        self.lineEdit_DIJKSTRA_end.setMinimumSize(QtCore.QSize(35, 30))
        self.lineEdit_DIJKSTRA_end.setMaximumSize(QtCore.QSize(35, 30))
        self.lineEdit_DIJKSTRA_end.setStyleSheet(
            'QLineEdit{\n    background-color: transparent;\n    border: none;\n    border-bottom: 2px solid white;\n    border-bottom-style: solid; \n    color:  white;\n    font: 63 14pt "Segoe UI Semibold";\n}')
        self.lineEdit_DIJKSTRA_end.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DIJKSTRA_end.setObjectName("lineEdit_DIJKSTRA_end")
        self.horizontalLayout_10.addWidget(self.lineEdit_DIJKSTRA_end)
        self.pushButton_clear_DIJKSTRA = QtWidgets.QPushButton(self.frame_DIJKSTRA)
        self.pushButton_clear_DIJKSTRA.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_clear_DIJKSTRA.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_clear_DIJKSTRA.setStyleSheet("QPushButton{"
                                                     "background-color: transparent;\nborder-radius: 5px;\n}"
                                                     "QPushButton::hover{\nbackground-color: rgb(44, 47, 51);\n}")
        self.pushButton_clear_DIJKSTRA.setIcon(QtGui.QIcon("icons/cil-remove.png"))
        self.pushButton_clear_DIJKSTRA.setObjectName("pushButton_clear_DIJKSTRA")
        self.horizontalLayout_10.addWidget(self.pushButton_clear_DIJKSTRA)
        self.verticalLayout_0.addWidget(self.frame_DIJKSTRA)
        self.frame_directed_undirected = QtWidgets.QFrame(self)
        self.frame_directed_undirected.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_directed_undirected.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_directed_undirected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_directed_undirected.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_directed_undirected.setObjectName("frame_directed_undirected")
        self.horizontalLayout_6_0 = QtWidgets.QHBoxLayout(self.frame_directed_undirected)
        self.horizontalLayout_6_0.setObjectName("horizontalLayout_6_0")
        self.pushButton_directed = QtWidgets.QPushButton(self.frame_directed_undirected)
        self.pushButton_directed.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_directed.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.pushButton_directed.setFont(font)
        self.pushButton_directed.setObjectName("pushButton_directed")
        self.horizontalLayout_6_0.addWidget(self.pushButton_directed)
        self.pushButton_undirected = QtWidgets.QPushButton(self.frame_directed_undirected)
        self.pushButton_undirected.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_undirected.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.pushButton_undirected.setFont(font)
        self.pushButton_undirected.setObjectName("pushButton_undirected")
        self.horizontalLayout_6_0.addWidget(self.pushButton_undirected)
        self.verticalLayout_0.addWidget(self.frame_directed_undirected)
        self.pushButton_run_commands = QtWidgets.QPushButton(self)
        self.pushButton_run_commands.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_run_commands.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.pushButton_run_commands.setFont(font)
        self.pushButton_run_commands.setIcon(QtGui.QIcon("icons/cil-terminal.png"))
        self.pushButton_run_commands.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_run_commands.setStyleSheet(
            "QPushButton{\n    background-color: transparent;\n    border-radius: 10px;\n    color: white;\n}\nQPushButton::hover{\n    background-color: rgb(44, 47, 51);\n}QPushButton::pressed{\n    background-color: rgb(66, 69, 74);\n}")
        self.pushButton_run_commands.setObjectName("pushButton_run_commands")
        self.verticalLayout_0.addWidget(self.pushButton_run_commands)

        self.pushButton_user_algorithm = QtWidgets.QPushButton(self)
        self.pushButton_user_algorithm.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_user_algorithm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.pushButton_user_algorithm.setFont(font)
        self.pushButton_user_algorithm.setIcon(QtGui.QIcon("icons/cil-terminal.png"))  # Optional: Add an icon
        self.pushButton_user_algorithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_user_algorithm.setStyleSheet(
            "QPushButton{\n    background-color: transparent;\n    border-radius: 10px;\n    color: white;\n}\nQPushButton::hover{\n    background-color: rgb(44, 47, 51);\n}QPushButton::pressed{\n    background-color: rgb(66, 69, 74);\n}")
        self.pushButton_user_algorithm.setObjectName("pushButton_user_algorithm")
        self.verticalLayout_0.addWidget(self.pushButton_user_algorithm)

        self.pushButton_save_graph = QtWidgets.QPushButton(self)
        self.pushButton_save_graph.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_save_graph.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Happy School")
        font.setPointSize(14)
        self.pushButton_save_graph.setFont(font)
        self.pushButton_save_graph.setIcon(QtGui.QIcon("icons/cil-save.png"))
        self.pushButton_save_graph.setText("Save")
        self.pushButton_save_graph.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_save_graph.setStyleSheet(
            "QPushButton{\n    background-color: transparent;\n    border-radius: 10px;\n    color: white;\n}\nQPushButton::hover{\n    background-color: rgb(44, 47, 51);\n}QPushButton::pressed{\n    background-color: rgb(66, 69, 74);\n}")
        self.pushButton_save_graph.setObjectName("pushButton_save_graph")
        self.verticalLayout_0.addWidget(self.pushButton_save_graph)
        spacerItem = QtWidgets.QSpacerItem(17, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_0.addItem(spacerItem)
        # self.horizontalLayout_9.addWidget(self.frame_change_settings)

        _translate = QtCore.QCoreApplication.translate
        self.label_force_mode.setText(_translate("ConfigPage", "Force mode"))
        self.pushButton_force_mode.setText(_translate("ConfigPage", "PushButton"))
        self.label_node_radius.setText(_translate("ConfigPage", "Node radius"))
        self.label_DFS.setText(_translate("ConfigPage", "DFS"))
        self.label_BFS.setText(_translate("ConfigPage", "BFS"))
        self.label_DIJKSTRA.setText(_translate("ConfigPage", "SHORTEST PATH"))
        self.pushButton_directed.setText(_translate("ConfigPage", "Directed"))
        self.pushButton_undirected.setText(_translate("ConfigPage", "Undirected"))
        self.pushButton_run_commands.setText(_translate("ConfigPage", "Run Algorithms"))
        self.pushButton_user_algorithm.setText(_translate("ConfigPage", "Run Custom Algorithm"))
